# Generated by Django 4.2.1 on 2023-05-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0002_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Product_favorites',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
