# Generated by Django 4.2.1 on 2023-05-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_product_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Product_favorites',
            new_name='product_favorites',
        ),
    ]
